name: Test the action

on:
    workflow_dispatch:
    push:
        branches:
            - "**"

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Send a test webhook
              uses: ./
              with:
                  webhook-url: ${{ secrets.RELEASE_WEBHOOK }}
                  changelog: |
                      - Fixed bugs
                      - Probably still have like a lot more bugs left to fix in this mod to be honest lol
                      - Tweaked this one weird setting
                      - Soggy mod incompatible
                      - This changelog was just a test
